spring:
  application:
    name: DEPARTMENT-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/    
    
     
management:
  tracing:
    sampling:
      probability: 1.0 
